server:
  port: 20430

spring:
  application.name: scheduler-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: angularpay
      username: service_account
      password: service_account_password
      authentication-database: angularpay

angularpay:
  pageSize: 50
  codecSizeInMB: 50
  executePastPending: true
  redis:
    host: localhost
    port: 6379
    timeout: 10000
